baseURL = "https://okuzawats.com/"
theme = "awesome"
languageCode = "ja-jp"
DefaultContentLanguage = "ja"
copyright = 'Â© 2019 okuzawats'

[params]
  author = "okuzawats"
  favicon = "favicon.png"

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    title = "okuzawats blog"
    [languages.en.params]
      description = "Mobile Application Development SwampğŸ’€"
  [languages.ja]
    languageName = "Japanese"
    weight = 20
    title = "okuzawatsã®æ—¥è¨˜"
    [languages.ja.params]
      description = "ãƒ¢ãƒã‚¤ãƒ«ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³é–‹ç™ºã®æ²¼ğŸ’€"

[menu]
  [[menu.main]]
  name = "About MeğŸ¤–"
  identifier = "about"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "BlogğŸ“"
  identifier = "blog"
  weight = 100
  url = "/blog/"

  [[menu.main]]
  name = "RSSğŸ“»"
  identifier = "rss"
  weight = 300
  url = "/index.xml"

[taxonomies]
  category = "categories"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "categories"
    weight = 100

[markup]
  [markup.highlight]
    style = "catppuccin-latte"
